name: "Build venv"
description: "Build a Python3 virtual environment, install the application and dependencies, and save the venv as an artifact"
inputs:
  runner-user:
    description: "User ID of the github runner. Used to correct permissions when executing commands inside Docker container."
    required: false
runs:
  using: composite
  steps:
    - name: Create Virtual Environment
      shell: bash
      run: |
        python3 -m venv venv
        venv/bin/pip install --upgrade pip "pipenv==2022.4.8"
    - name: Install Dependencies
      shell: bash
      run: |
        venv/bin/pipenv install
        if [ -d tamucas-client ]
        then 
          venv/bin/pip install ./tamucas-client
        fi
        if [ -d tamu-account ]
        then
          venv/bin/pip install ./tamu-account
        fi
        if [ -d Gateway-Services ]
        then
          venv/bin/pip install ./Gateway-Services
        fi
    - name: Install Application
      shell: bash
      run: |
        venv/bin/pip install .
        git log --pretty=format:"%s%n%b" > venv/RELEASE-NOTES.txt
    - name: Create tarball for venv
      shell: bash
      run: tar -cJf venv.tar.xz venv
    - name: Save venv as artifact
      uses: actions/upload-artifact@v2
      with:
        name: venv
        path: venv.tar.xz
    - name: Fix permissions if building inside docker container
      shell: bash
      run: if [ ! -z "${{ inputs.runner-user }}" ] ; then chown -R ${{ inputs.runner-user }} . ; fi
